---
title: "Predict disease index LemnaTec data cross-validation"
author: Florian Tanner
date: "`r format(Sys.time())`"
output: html_document
---


```{r}
.libPaths("C:/R-packages2")
rm(list=ls())
```


## Load packages

```{r,  message = FALSE}
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
library(tidymodels)
library(doParallel)
library(ggstatsplot)
library(patchwork)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Set year

```{r}
year_to_run = "2021"
```

## Load data 

```{r}
traits <- read_csv("../psa_analysis/out/data/traits.csv")
scores <- read_csv("../raw_data/scores/scores_2020.csv") |> 
  bind_rows(read_csv("../raw_data/scores/scores_2021.csv"))
```

## Correlation traits

```{r}
lemna_data <- traits |> 
  select(-id_with_controls) |> 
  left_join(scores |> rename(plotId = id_tag) |> select(plotId, di)) |> 
  filter(treatment == "Infected",
         !is.na(di)) 

lemna_data_2020 <- lemna_data |> filter(experiment == 2020)
lemna_data_2021 <- lemna_data |> filter(experiment == 2021)
```

```{r}
names(lemna_data)

cor_mat <- lemna_data |> 
  rename(DI = di) |> 
  rename_with(~str_replace(., "_", " "), .cols = everything()) |> 
  rename_with(~str_replace(., "_", "-"), .cols = everything()) |> 
  select(-plotId, -treatment) 
```

```{r, fig.height = 7}
ggstatsplot_p <- cor_mat |>   
  ggstatsplot::grouped_ggcorrmat(grouping.var = experiment, plotgrid.args = list(nrow = 2), ggcorrplot.args = list(insig = "pch"))
ggstatsplot_p
ggsave(plot = ggstatsplot_p, filename = "out/graphs/lemna_di_cor_mat.pdf", device = "pdf", units = "cm", width = 12, height= 16, scale = 2)
```


```{r, fig.height=6}
mat_data_2020 <- cor_mat |> filter(experiment == 2020) |> 
  select(-experiment)

p_2020 <- ggstatsplot::ggcorrmat(mat_data_2020, ggcorrplot.args = list(lab_col = NA, pch.col = NA, lab_size = 3.5))

label_2020 <- p_2020$plot_env$label
pval_2020 <- p_2020$data$pvalue

new_label_2020 <- data.frame(label = label_2020, pval = pval_2020) |> 
  mutate(new_label_2020 = case_when(pval_2020 > 0.05 ~ paste(label_2020, "\nn.s."),
                               pval_2020 <= 0.05 & pval_2020 > 0.01 ~ paste(label_2020, "\n*"),
                               pval_2020 <= 0.01 & pval_2020 > 0.001 ~ paste(label_2020, "\n**"),
                               pval_2020 <= 0.001 ~ paste(label_2020, "\n***"))) |> 
  pull(new_label_2020)

p_2020$data$label <- new_label_2020

p_2020 <- p_2020 +
  geom_text(aes(label = new_label_2020), size = 3.5) +
  labs(title = "2020") +
  theme(plot.caption = element_blank())

p_2020
```
```{r, fig.height=6}
mat_data_2021 <- cor_mat |> filter(experiment == 2021) |> 
  select(-experiment)

p_2021 <- ggstatsplot::ggcorrmat(mat_data_2021, 
                                 ggcorrplot.args = list(lab_col = NA, pch.col = NA, lab_size = 3.5))

label_2021 <- p_2021$plot_env$label
pval_2021 <- p_2021$data$pvalue

new_label_2021 <- data.frame(label = label_2021, pval = pval_2021) |> 
  mutate(new_label_2021 = case_when(pval_2021 > 0.05 ~ paste(label_2021, "\nn.s."),
                                    pval_2021 <= 0.05 & pval_2021 > 0.01 ~ paste(label_2021, "\n*"),
                                    pval_2021 <= 0.01 & pval_2021 > 0.001 ~ paste(label_2021, "\n**"),
                                    pval_2021 <= 0.001 ~ paste(label_2021, "\n***"))) |> 
  pull(new_label_2021)

p_2021$data$label <- new_label_2021

p_2021 <- p_2021 +
  geom_text(aes(label = new_label_2021), size = 3.5) +
  labs(title = "2021") +
  theme(plot.caption = element_blank())

p_2021
```

```{r}
p_cor <- p_2020 + p_2021 + plot_layout(nrow =2) + labs(caption = "Test")
ggsave(plot = p_cor, filename = "out/graphs/lemna_di_cor_mat_ns_labels.pdf", device = "pdf", units = "cm", width = 12, height= 16, scale = 2)
```

## vfold_CV


### Set seed, amount of folds and repeats

```{r}
seed <- 123
n_folds <- 5
n_repeats <- 5
```



```{r}
folds_2020 <- vfold_cv(lemna_data_2020 , v = n_folds, repeats = n_repeats, strata = di)
folds_2021 <- vfold_cv(lemna_data_2021, v = n_folds, repeats = n_repeats, strata = di)
```

## Linear model PSA_0, RGR_7_14, RGR_14_21

```{r}
linreg_spec <- linear_reg() |> 
  set_engine("lm") |> 
  set_mode("regression")

linear_fits_2020 <- linreg_spec |> 
  fit_resamples(di ~ PSA_0 + RGR_7_14 + RGR_14_21, resamples = folds_2020)

linear_fits_2021 <- linreg_spec |> 
  fit_resamples(di ~ PSA_0 + RGR_7_14 + RGR_14_21, resamples = folds_2021)
```

### Full random forest model

```{r}
ref_recipe <- recipe((di ~ .), 
                       data = lemna_data)  |>
    update_role(plotId, new_role = "ID") |> 
  update_role(treatment, new_role = "ID") |> 
    step_center(all_predictors()) |>
    step_scale(all_predictors()) |>
    step_zv(all_predictors()) 

rf_spec <- rand_forest() |> 
    set_engine("ranger") |> 
    set_mode("regression") |> 
    translate()

rf_wf <- workflow() |> 
  add_model(rf_spec) |> 
  add_recipe(ref_recipe)

set.seed(seed)
rf_fits_2020 <- rf_wf |> fit_resamples(resamples = folds_2020)
rf_fits_2021 <- rf_wf |> fit_resamples(resamples = folds_2021)
```

## Bind metrics

```{r}
lemna_cv_metrics <- rf_fits_2020 |> collect_metrics() |> mutate(experiment = 2020, model = "RF") |> 
  bind_rows(rf_fits_2021 |> collect_metrics() |> mutate(experiment = 2021, model = "RF")) |> 
  bind_rows(linear_fits_2020 |> collect_metrics() |> mutate(experiment = 2020, model = "Linreg")) |> 
  bind_rows(linear_fits_2021 |> collect_metrics() |> mutate(experiment = 2021, model = "Linreg")) |> 
  mutate(label = paste(round(mean, 2), "\u00b1", round(std_err, 2)))

lemna_cv_metrics
```

## Train on 2020, test on 2021

### Fit full models

```{r}
linreg_2020_trained <- linreg_spec |> 
  fit(di ~ PSA_0 + RGR_7_14 + RGR_14_21, data = lemna_data_2020)

set.seed(seed)

rf_2020_trained <- rf_wf |> 
  fit(lemna_data_2020)
```

### Predict 2021

```{r}
lemna_predictions_2021 <- predict(linreg_2020_trained, lemna_data_2021) |> 
  rename(linreg_pred = .pred) |> 
  bind_cols(predict(rf_2020_trained, lemna_data_2021) |> 
  rename(rf_pred = .pred) ) |> 
  bind_cols(lemna_data_2021)
  
write_csv(lemna_predictions_2021, "out/predictions/lemna_predictions_2021.csv") 
```


## Train on 2021, test on 2020

### Fit full models

```{r}
linreg_2021_trained <- linreg_spec |> 
  fit(di ~ PSA_0 + RGR_7_14 + RGR_14_21, data = lemna_data_2021)

set.seed(seed)

rf_2021_trained <- rf_wf |> 
  fit(lemna_data_2021)
```

### Predict 2020

```{r}
lemna_predictions_2020 <- predict(linreg_2021_trained, lemna_data_2020) |> 
  rename(linreg_pred = .pred) |> 
  bind_cols(predict(rf_2021_trained, lemna_data_2020) |> 
  rename(rf_pred = .pred) ) |> 
  bind_cols(lemna_data_2020)
  
write_csv(lemna_predictions_2020, "out/predictions/lemna_predictions_2020.csv") 
```

```{r}
sessionInfo()
```
