---
title: "Early detection of AB"
author: Florian Tanner
date: "`r format(Sys.time())`"
output: html_document
---


```{r}
.libPaths("C:/R-packages2")
rm(list=ls())
```


## Load packages

```{r,  message = FALSE}
library(tidyverse)
library(ggplot2); theme_set(theme_bw())
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load data

```{r}
scores <- read_csv(paste("../raw_data/scores/scores_2021.csv", sep = ""))
hyperspec_full <- read_csv(paste("../pre_processing/hyperspectral/out/2021/raw_and_smoothed_full.csv", sep = ""))
```

```{r}
ref_wide <- hyperspec_full |> 
  select(-reflectance_smoothed) |> 
  filter(date == as.Date("2021-06-15 UTC"),
         !is.na(reflectance_raw)) |> 
  pivot_wider(id_cols = id_tag,
              names_from = wavelength, 
              values_from = reflectance_raw)

cor_mat <- 
  as.data.frame(cor(ref_wide |> select(-id_tag), method = "pearson"))

cor_mat$Wavelength <- row.names(cor_mat)

plot_mat <- cor_mat |> 
  pivot_longer(cols = -Wavelength, names_to = "cor_ref", values_to = "correlation") |> 
  mutate(Wavelength = as.numeric(Wavelength), 
         cor_ref = as.numeric(cor_ref),
         r_squared = correlation * correlation)

p_cor <- plot_mat |> 
  ggplot(aes(x= Wavelength, y = cor_ref, fill = r_squared)) +
  geom_tile(data = plot_mat |> filter(Wavelength < 1001, cor_ref < 1001),
            height = 1.4, width = 1.4) +
  geom_tile(data = plot_mat |> filter(Wavelength > 1001, cor_ref > 1001),
            height = 5.65, width = 5.65) +
  geom_tile(data = plot_mat |> filter(Wavelength > 1001, cor_ref < 1001),
            height = 1.4, width = 5.65) +
  geom_tile(data = plot_mat |> filter(Wavelength < 1001, cor_ref > 1001),
            height = 5.65, width = 1.4) +
  paletteer::scale_fill_paletteer_c("ggthemes::Blue-Green Sequential", limits= c(0,1)) +
  labs(x = "Wavelength [nm]",y = "Wavelength [nm]", fill = "Squared Pearson's correlation coefficient")+
  theme(legend.position = "bottom")

p_cor

ggsave(p_cor, filename = "out/band_pair_correlation.pdf",
       device = "pdf", units = "cm", width = 10, height = 12, limitsize = F, scale = 1.3)
ggsave(p_cor, filename = "out/band_pair_correlation.png",
       device = "png", units = "cm", width = 10, height = 12, limitsize = F, scale = 1.3)
```


```{r}
sessionInfo()
```
